server:
  port: 8067

spring:
    datasource:
        name: test
        url: jdbc:mysql://129.211.46.218:3306/overseas?characterEncoding=UTF-8
        username: root
        password: lulijie95144
        driver-class-name: com.mysql.jdbc.Driver
    thymeleaf:
        prefix: classpath:/templates/
        suffix: .html
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
