package com.lc.overseas.dao;

import com.lc.overseas.pojo.commentman_order;

import java.util.List;

public interface commentman_orderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentman_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentman_order
     *
     * @mbggenerated
     */
    int insert(commentman_order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentman_order
     *
     * @mbggenerated
     */
    int insertSelective(commentman_order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentman_order
     *
     * @mbggenerated
     */
    List<commentman_order> selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentman_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(commentman_order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentman_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(commentman_order record);
}