package com.lc.overseas.pojo;

import java.util.Date;

public class commentman_order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentman_order.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentman_order.ordertime
     *
     * @mbggenerated
     */
    private Date ordertime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentman_order.zhuanyuan
     *
     * @mbggenerated
     */
    private String zhuanyuan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentman_order.mainpage
     *
     * @mbggenerated
     */
    private String mainpage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentman_order.customnum
     *
     * @mbggenerated
     */
    private String customnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentman_order.product
     *
     * @mbggenerated
     */
    private String product;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentman_order.shop
     *
     * @mbggenerated
     */
    private String shop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentman_order.orderno
     *
     * @mbggenerated
     */
    private String orderno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentman_order.orderremark
     *
     * @mbggenerated
     */
    private String orderremark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentman_order.paypalacount
     *
     * @mbggenerated
     */
    private String paypalacount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentman_order.isliuping
     *
     * @mbggenerated
     */
    private String isliuping;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentman_order.blacklist
     *
     * @mbggenerated
     */
    private String blacklist;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentman_order.id
     *
     * @return the value of commentman_order.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentman_order.id
     *
     * @param id the value for commentman_order.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentman_order.ordertime
     *
     * @return the value of commentman_order.ordertime
     *
     * @mbggenerated
     */
    public Date getOrdertime() {
        return ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentman_order.ordertime
     *
     * @param ordertime the value for commentman_order.ordertime
     *
     * @mbggenerated
     */
    public void setOrdertime(Date ordertime) {
        this.ordertime = ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentman_order.zhuanyuan
     *
     * @return the value of commentman_order.zhuanyuan
     *
     * @mbggenerated
     */
    public String getZhuanyuan() {
        return zhuanyuan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentman_order.zhuanyuan
     *
     * @param zhuanyuan the value for commentman_order.zhuanyuan
     *
     * @mbggenerated
     */
    public void setZhuanyuan(String zhuanyuan) {
        this.zhuanyuan = zhuanyuan == null ? null : zhuanyuan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentman_order.mainpage
     *
     * @return the value of commentman_order.mainpage
     *
     * @mbggenerated
     */
    public String getMainpage() {
        return mainpage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentman_order.mainpage
     *
     * @param mainpage the value for commentman_order.mainpage
     *
     * @mbggenerated
     */
    public void setMainpage(String mainpage) {
        this.mainpage = mainpage == null ? null : mainpage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentman_order.customnum
     *
     * @return the value of commentman_order.customnum
     *
     * @mbggenerated
     */
    public String getCustomnum() {
        return customnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentman_order.customnum
     *
     * @param customnum the value for commentman_order.customnum
     *
     * @mbggenerated
     */
    public void setCustomnum(String customnum) {
        this.customnum = customnum == null ? null : customnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentman_order.product
     *
     * @return the value of commentman_order.product
     *
     * @mbggenerated
     */
    public String getProduct() {
        return product;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentman_order.product
     *
     * @param product the value for commentman_order.product
     *
     * @mbggenerated
     */
    public void setProduct(String product) {
        this.product = product == null ? null : product.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentman_order.shop
     *
     * @return the value of commentman_order.shop
     *
     * @mbggenerated
     */
    public String getShop() {
        return shop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentman_order.shop
     *
     * @param shop the value for commentman_order.shop
     *
     * @mbggenerated
     */
    public void setShop(String shop) {
        this.shop = shop == null ? null : shop.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentman_order.orderno
     *
     * @return the value of commentman_order.orderno
     *
     * @mbggenerated
     */
    public String getOrderno() {
        return orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentman_order.orderno
     *
     * @param orderno the value for commentman_order.orderno
     *
     * @mbggenerated
     */
    public void setOrderno(String orderno) {
        this.orderno = orderno == null ? null : orderno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentman_order.orderremark
     *
     * @return the value of commentman_order.orderremark
     *
     * @mbggenerated
     */
    public String getOrderremark() {
        return orderremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentman_order.orderremark
     *
     * @param orderremark the value for commentman_order.orderremark
     *
     * @mbggenerated
     */
    public void setOrderremark(String orderremark) {
        this.orderremark = orderremark == null ? null : orderremark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentman_order.paypalacount
     *
     * @return the value of commentman_order.paypalacount
     *
     * @mbggenerated
     */
    public String getPaypalacount() {
        return paypalacount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentman_order.paypalacount
     *
     * @param paypalacount the value for commentman_order.paypalacount
     *
     * @mbggenerated
     */
    public void setPaypalacount(String paypalacount) {
        this.paypalacount = paypalacount == null ? null : paypalacount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentman_order.isliuping
     *
     * @return the value of commentman_order.isliuping
     *
     * @mbggenerated
     */
    public String getIsliuping() {
        return isliuping;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentman_order.isliuping
     *
     * @param isliuping the value for commentman_order.isliuping
     *
     * @mbggenerated
     */
    public void setIsliuping(String isliuping) {
        this.isliuping = isliuping == null ? null : isliuping.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentman_order.blacklist
     *
     * @return the value of commentman_order.blacklist
     *
     * @mbggenerated
     */
    public String getBlacklist() {
        return blacklist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentman_order.blacklist
     *
     * @param blacklist the value for commentman_order.blacklist
     *
     * @mbggenerated
     */
    public void setBlacklist(String blacklist) {
        this.blacklist = blacklist == null ? null : blacklist.trim();
    }
}