package com.lc.overseas.pojo;

import java.util.Date;

public class commentman {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentman.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentman.detail
     *
     * @mbggenerated
     */
    private String detail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentman.fbid
     *
     * @mbggenerated
     */
    private String fbid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentman.country
     *
     * @mbggenerated
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentman.paypal
     *
     * @mbggenerated
     */
    private String paypal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentman.prolink
     *
     * @mbggenerated
     */
    private String prolink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentman.proname
     *
     * @mbggenerated
     */
    private String proname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentman.mainpagenum
     *
     * @mbggenerated
     */
    private String mainpagenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentman.countbuy
     *
     * @mbggenerated
     */
    private Integer countbuy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentman.liuping
     *
     * @mbggenerated
     */
    private Integer liuping;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentman.shouhou
     *
     * @mbggenerated
     */
    private Integer shouhou;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentman.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentman.grade
     *
     * @mbggenerated
     */
    private String grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentman.earlybuy
     *
     * @mbggenerated
     */
    private Date earlybuy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentman.nearbuy
     *
     * @mbggenerated
     */
    private Date nearbuy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentman.id
     *
     * @return the value of commentman.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentman.id
     *
     * @param id the value for commentman.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentman.detail
     *
     * @return the value of commentman.detail
     *
     * @mbggenerated
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentman.detail
     *
     * @param detail the value for commentman.detail
     *
     * @mbggenerated
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentman.fbid
     *
     * @return the value of commentman.fbid
     *
     * @mbggenerated
     */
    public String getFbid() {
        return fbid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentman.fbid
     *
     * @param fbid the value for commentman.fbid
     *
     * @mbggenerated
     */
    public void setFbid(String fbid) {
        this.fbid = fbid == null ? null : fbid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentman.country
     *
     * @return the value of commentman.country
     *
     * @mbggenerated
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentman.country
     *
     * @param country the value for commentman.country
     *
     * @mbggenerated
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentman.paypal
     *
     * @return the value of commentman.paypal
     *
     * @mbggenerated
     */
    public String getPaypal() {
        return paypal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentman.paypal
     *
     * @param paypal the value for commentman.paypal
     *
     * @mbggenerated
     */
    public void setPaypal(String paypal) {
        this.paypal = paypal == null ? null : paypal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentman.prolink
     *
     * @return the value of commentman.prolink
     *
     * @mbggenerated
     */
    public String getProlink() {
        return prolink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentman.prolink
     *
     * @param prolink the value for commentman.prolink
     *
     * @mbggenerated
     */
    public void setProlink(String prolink) {
        this.prolink = prolink == null ? null : prolink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentman.proname
     *
     * @return the value of commentman.proname
     *
     * @mbggenerated
     */
    public String getProname() {
        return proname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentman.proname
     *
     * @param proname the value for commentman.proname
     *
     * @mbggenerated
     */
    public void setProname(String proname) {
        this.proname = proname == null ? null : proname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentman.mainpagenum
     *
     * @return the value of commentman.mainpagenum
     *
     * @mbggenerated
     */
    public String getMainpagenum() {
        return mainpagenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentman.mainpagenum
     *
     * @param mainpagenum the value for commentman.mainpagenum
     *
     * @mbggenerated
     */
    public void setMainpagenum(String mainpagenum) {
        this.mainpagenum = mainpagenum == null ? null : mainpagenum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentman.countbuy
     *
     * @return the value of commentman.countbuy
     *
     * @mbggenerated
     */
    public Integer getCountbuy() {
        return countbuy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentman.countbuy
     *
     * @param countbuy the value for commentman.countbuy
     *
     * @mbggenerated
     */
    public void setCountbuy(Integer countbuy) {
        this.countbuy = countbuy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentman.liuping
     *
     * @return the value of commentman.liuping
     *
     * @mbggenerated
     */
    public Integer getLiuping() {
        return liuping;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentman.liuping
     *
     * @param liuping the value for commentman.liuping
     *
     * @mbggenerated
     */
    public void setLiuping(Integer liuping) {
        this.liuping = liuping;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentman.shouhou
     *
     * @return the value of commentman.shouhou
     *
     * @mbggenerated
     */
    public Integer getShouhou() {
        return shouhou;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentman.shouhou
     *
     * @param shouhou the value for commentman.shouhou
     *
     * @mbggenerated
     */
    public void setShouhou(Integer shouhou) {
        this.shouhou = shouhou;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentman.remark
     *
     * @return the value of commentman.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentman.remark
     *
     * @param remark the value for commentman.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentman.grade
     *
     * @return the value of commentman.grade
     *
     * @mbggenerated
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentman.grade
     *
     * @param grade the value for commentman.grade
     *
     * @mbggenerated
     */
    public void setGrade(String grade) {
        this.grade = grade == null ? null : grade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentman.earlybuy
     *
     * @return the value of commentman.earlybuy
     *
     * @mbggenerated
     */
    public Date getEarlybuy() {
        return earlybuy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentman.earlybuy
     *
     * @param earlybuy the value for commentman.earlybuy
     *
     * @mbggenerated
     */
    public void setEarlybuy(Date earlybuy) {
        this.earlybuy = earlybuy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentman.nearbuy
     *
     * @return the value of commentman.nearbuy
     *
     * @mbggenerated
     */
    public Date getNearbuy() {
        return nearbuy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentman.nearbuy
     *
     * @param nearbuy the value for commentman.nearbuy
     *
     * @mbggenerated
     */
    public void setNearbuy(Date nearbuy) {
        this.nearbuy = nearbuy;
    }
}